// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class AppAssets {
  static const String package = 'trip_demo';

  static const String ic_logo_png = 'images/icon/ic_logo.png';
}
