include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/src/utils/app_assets.dart

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    library_prefixes: false
    constant_identifier_names: false
    prefer_const_constructors: true
    annotate_overrides: true
    overridden_fields: false